import { recommendBucket } from "./gonogo";
import type { Opportunity } from "./types";

function isoOffset(days: number, hours = 10): string {
  const d = new Date();
  d.setHours(hours, 0, 0, 0);
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

export function seedOpportunities(): Opportunity[] {
  const raw: Omit<Opportunity, "bucket" | "stage">[] = [
    {
      id: "demo-01",
      title: "Enterprise Service Desk and End-User Computing Support",
      noticeId: "W91RUS26R0041",
      agency: "Department of the Army",
      office: "ACC-APG",
      naics: "541513",
      psc: "DJ01",
      noticeType: "solicitation",
      setAside: "total-sb",
      postedAt: isoOffset(-1),
      dueAt: isoOffset(18, 14),
      estValue: 48_000_000,
      place: "Fort Huachuca, AZ (hybrid)",
      incumbent: "Northwind Mission Support",
      notes: "Follow-on to a 5-year desk-side / service-desk effort. Draft PWS emphasizes ITIL 4 and asset management.",
      sample: true,
    },
    {
      id: "demo-02",
      title: "Sources Sought — Cloud Migration and ATO Support for Benefits Platforms",
      noticeId: "36C10B26N0088",
      agency: "Department of Veterans Affairs",
      office: "NCO 22",
      naics: "541512",
      psc: "DA01",
      noticeType: "sources-sought",
      setAside: "sdvosb",
      postedAt: isoOffset(0, 7),
      dueAt: isoOffset(9, 17),
      estValue: 22_000_000,
      place: "Remote / Austin, TX",
      notes: "VA is mapping vendors before a FY27 RFP. Capability statement + three relevant ATOs requested.",
      sample: true,
    },
    {
      id: "demo-03",
      title: "A/E Services for Hangar Recapitalization, Multiple CONUS Locations",
      noticeId: "FA890326R2210",
      agency: "Department of the Air Force",
      office: "AFCEC",
      naics: "541330",
      psc: "C211",
      noticeType: "presolicitation",
      setAside: "unrestricted",
      postedAt: isoOffset(-2),
      dueAt: isoOffset(45, 15),
      estValue: 85_000_000,
      place: "CONUS — various installations",
      incumbent: "Helios + Brant A/E JV",
      notes: "Industry day announced. IDIQ with 4-year base. SF 330 will drive the evaluation.",
      sample: true,
    },
    {
      id: "demo-04",
      title: "Award — National Background Investigation IT Operations",
      noticeId: "DHS-CISA-26-A-019",
      agency: "Department of Homeland Security",
      office: "CISA",
      naics: "541512",
      psc: "DJ01",
      noticeType: "award",
      setAside: "unrestricted",
      postedAt: isoOffset(0, 6),
      dueAt: isoOffset(0, 6),
      estValue: 312_000_000,
      place: "NCR / remote",
      incumbent: "Awardee: Meridian Federal Systems",
      notes: "Log competitor, ceiling, and NAICS. Unrestricted; incumbent displaced.",
      sample: true,
    },
    {
      id: "demo-05",
      title: "Facilities Operations and Maintenance, Medical Center Campus",
      noticeId: "36C25626Q0144",
      agency: "Department of Veterans Affairs",
      office: "NCO 16",
      naics: "561210",
      psc: "Z1DA",
      noticeType: "solicitation",
      setAside: "8a",
      postedAt: isoOffset(-3),
      dueAt: isoOffset(12, 13),
      estValue: 19_400_000,
      place: "Houston, TX",
      incumbent: "Harbor Path 8(a)",
      notes: "RFQ under FAR 8.4 / GSA. QASP attached. Staffing plan will decide it.",
      sample: true,
    },
    {
      id: "demo-06",
      title: "RFI — Zero Trust Architecture Implementation Across Civilian Bureaus",
      noticeId: "OS-OCIO-26-RFI-07",
      agency: "Department of the Interior",
      office: "OCIO",
      naics: "541519",
      psc: "DH01",
      noticeType: "rfi",
      setAside: "unrestricted",
      postedAt: isoOffset(-1, 16),
      dueAt: isoOffset(14, 17),
      estValue: 40_000_000,
      place: "Washington, DC / remote",
      notes: "Questions are really about small-business on-ramp and CMMC level. Shape the later PWS.",
      sample: true,
    },
    {
      id: "demo-07",
      title: "Custom Application Development for Grants Management Modernization",
      noticeId: "75N98026R00032",
      agency: "Department of Health and Human Services",
      office: "NIH / OD",
      naics: "541511",
      psc: "DA01",
      noticeType: "solicitation",
      setAside: "total-sb",
      postedAt: isoOffset(0, 8),
      dueAt: isoOffset(21, 13),
      estValue: 8_600_000,
      place: "Bethesda, MD (hybrid)",
      notes: "Agile, 8 sprints described. Section M is 60% technical, 25% past performance, 15% price.",
      sample: true,
    },
    {
      id: "demo-08",
      title: "Electrical Upgrades and Generator Replacement, Border Stations",
      noticeId: "47PH0826B0009",
      agency: "General Services Administration",
      office: "PBS Region 9",
      naics: "238210",
      psc: "Z2AZ",
      noticeType: "solicitation",
      setAside: "hubzone",
      postedAt: isoOffset(-4),
      dueAt: isoOffset(7, 15),
      estValue: 3_200_000,
      place: "San Diego County, CA",
      notes: "IFB. Bonding required. Site visit was yesterday — late to the party unless you attended.",
      sample: true,
    },
    {
      id: "demo-09",
      title: "Program Management Support for Logistics Transformation",
      noticeId: "N00039-26-R-0044",
      agency: "Department of the Navy",
      office: "NAVWAR",
      naics: "541611",
      psc: "R408",
      noticeType: "solicitation",
      setAside: "unrestricted",
      postedAt: isoOffset(-2),
      dueAt: isoOffset(27, 14),
      estValue: 64_000_000,
      place: "San Diego, CA",
      incumbent: "Harborline Technical",
      notes: "Full FAR 15. Key personnel with TS. Likely 6–8 serious primes.",
      sample: true,
    },
    {
      id: "demo-10",
      title: "Special Notice — Industry Day for Wildland Fire Decision Support Software",
      noticeId: "1202SA26N0011",
      agency: "Department of Agriculture",
      office: "Forest Service",
      naics: "541511",
      psc: "DA01",
      noticeType: "special",
      setAside: "total-sb",
      postedAt: isoOffset(0, 9),
      dueAt: isoOffset(11, 12),
      estValue: 6_500_000,
      place: "Boise, ID / virtual",
      notes: "RSVP required. This is how you get on the vendor list before the RFP.",
      sample: true,
    },
    {
      id: "demo-11",
      title: "Justification — Bridge Contract for Help Desk, 8 months",
      noticeId: "47QTCA26J-BRIDGE",
      agency: "General Services Administration",
      office: "FAS",
      naics: "541513",
      psc: "DJ01",
      noticeType: "justification",
      setAside: "unrestricted",
      postedAt: isoOffset(-1, 11),
      dueAt: isoOffset(-1, 11),
      estValue: 4_800_000,
      place: "National Capital Region",
      incumbent: "Bridge to incumbent: Lumenpath Inc.",
      notes: "Recompete is slipping. Calendar the follow-on and start capture now.",
      sample: true,
    },
    {
      id: "demo-12",
      title: "Environmental Consulting for FUDS Site Investigations",
      noticeId: "W912DY26R0033",
      agency: "Department of the Army",
      office: "USACE",
      naics: "541620",
      psc: "F999",
      noticeType: "solicitation",
      setAside: "wosb",
      postedAt: isoOffset(-5),
      dueAt: isoOffset(16, 15),
      estValue: 14_200_000,
      place: "Multiple FUDS, Great Lakes",
      notes: "MATOC. Experience with MMRP and CERCLA needed. Teaming likely required.",
      sample: true,
    },
  ];

  return raw.map((o) => {
    const bucket = o.noticeType === "solicitation" ? "inbox" : recommendBucket(o.noticeType);
    const stage = bucket === "inbox" || bucket === "score" ? "triage" : bucket === "pass" ? "no-bid" : "triage";
    return { ...o, bucket, stage };
  });
}
