/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as OpportunityIdRouteImport } from './routes/opportunity.$id'
import { Route as PlaybookSlugRouteImport } from './routes/playbook.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityIdRoute = OpportunityIdRouteImport.update({
  id: '/opportunity/$id',
  path: '/opportunity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookSlugRoute = PlaybookSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PlaybookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/desk': typeof DeskRoute
  '/pipeline': typeof PipelineRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/opportunity/$id': typeof OpportunityIdRoute
  '/playbook/$slug': typeof PlaybookSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/desk': typeof DeskRoute
  '/pipeline': typeof PipelineRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/opportunity/$id': typeof OpportunityIdRoute
  '/playbook/$slug': typeof PlaybookSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/desk': typeof DeskRoute
  '/pipeline': typeof PipelineRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/opportunity/$id': typeof OpportunityIdRoute
  '/playbook/$slug': typeof PlaybookSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/desk'
    | '/pipeline'
    | '/playbook'
    | '/opportunity/$id'
    | '/playbook/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/desk'
    | '/pipeline'
    | '/playbook'
    | '/opportunity/$id'
    | '/playbook/$slug'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/desk'
    | '/pipeline'
    | '/playbook'
    | '/opportunity/$id'
    | '/playbook/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRoute
  DeskRoute: typeof DeskRoute
  PipelineRoute: typeof PipelineRoute
  PlaybookRoute: typeof PlaybookRouteWithChildren
  OpportunityIdRoute: typeof OpportunityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity/$id': {
      id: '/opportunity/$id'
      path: '/opportunity/$id'
      fullPath: '/opportunity/$id'
      preLoaderRoute: typeof OpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook/$slug': {
      id: '/playbook/$slug'
      path: '/$slug'
      fullPath: '/playbook/$slug'
      preLoaderRoute: typeof PlaybookSlugRouteImport
      parentRoute: typeof PlaybookRoute
    }
  }
}

interface PlaybookRouteChildren {
  PlaybookSlugRoute: typeof PlaybookSlugRoute
}

const PlaybookRouteChildren: PlaybookRouteChildren = {
  PlaybookSlugRoute: PlaybookSlugRoute,
}

const PlaybookRouteWithChildren = PlaybookRoute._addFileChildren(
  PlaybookRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRoute,
  DeskRoute: DeskRoute,
  PipelineRoute: PipelineRoute,
  PlaybookRoute: PlaybookRouteWithChildren,
  OpportunityIdRoute: OpportunityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
